


require:
  - rubocop-capybara
  - rubocop-rspec_rails
  - sevencop

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisplayCopNames: true
  NewCops: disable

Style/Documentation:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/MethodLength:
  Max: 20

Rspec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: 20

Rspec/Focus:
  AutoCorrect: false

RSpec/ContextWording:
    Enabled: false
