


require:
  - rubocop-capybara
  - rubocop-rspec_rails
  - sevencop

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisplayCopNames: true
  NewCops: disable
