version: '3'

tasks:
  rails:
    desc: Rails command
    cmd: |
      bin/rails {{.CLI_ARGS}}

  rails_c:
    desc: Rails console
    cmds:
      - bin/rails c

  dev:
    desc: Start development server
    cmds:
      - bin/rails s

  typegen:
    desc: Generate RBS files
    cmd: |
      bin/rails rbs:setup

  default:
    desc: ヘルプを表示する
    cmds:
      - task --list-all
